/*******************************************************************************
 * Copyright (c) 2006-2012 Bruno Ranschaert
 * Released under the MIT License: http://opensource.org/licenses/MIT
 * Library "jsontools"
 ******************************************************************************/
package com.sdicons.json.helper;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.annotation.ElementType;

/**
 * Annotate the constructor of the JavaBean that has to be used by the mapper
 * or the serializer to instantiate the bean. The argument list for the constructor 
 * has to be generated by the @JSONConstructorArgs annotated method. The two annotations
 * @JSONConstructor and @JSONConstructorArgs work together.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.CONSTRUCTOR)
public @interface JSONConstructor
{
}
